export const SELECTED_REQUEST = 'SELECTED_REQUEST'
export const FETCH_ALL_REQUESTS = 'FETCH_ALL_REQUESTS'
export const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS'
export const FETCH_REQUESTS_FAILURE = 'FETCH_REQUESTS_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS'
export const SIGNUP_REQUEST_FAILURE = 'SIGNUP_REQUEST_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS'
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE'


export const ADD_REQUEST = 'ADD_REQUEST'
export const ADD_REQUEST_SUCCESS = 'ADD_REQUEST_SUCCESS'
export const ADD_REQUEST_FAILURE = 'ADD_REQUEST_FAILURE'

